
testenv:
  image: societhy/localenv
  dns:
    - 8.8.8.8
  command: /usr/bin/supervisord -n -c /etc/supervisor/supervisor.conf -l /supervisord.log
  working_dir: /societhy
  ports:
    - "8800"  # unused
  #  - "27017:27017" # unused
    - "8545"  # geth json-rpc api
    - "30303"  # geth p2p protocol

  volumes:
    - ./code:/societhy/code:ro