module.exports = {
    layout1: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layout1/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layout1/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layout1/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layout1/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layout1/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/templates',     dest: "layout1/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/api',     dest: "layout1/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/i18n',    dest: "layout1/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/images',     dest: "layout1/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/config',      dest: "layout1/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/directives',      dest: "layout1/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/controllers',      dest: "layout1/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/js/filters',      dest: "layout1/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/views',     dest: "layout1/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/STANDARD/assets/css/themes',     dest: "layout1/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layout1/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-1/STANDARD/master/_index.min.html', dest : 'layout1/index.html'},
            {src: 'LAYOUT-1/STANDARD/favicon.ico', dest : 'layout1/favicon.ico'},
            {src: 'LAYOUT-1/STANDARD/upload.php', dest : 'layout1/upload.php'}
        ]
    },
    layoutrtl1: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layoutrtl1/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layoutrtl1/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layoutrtl1/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layoutrtl1/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layoutrtl1/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/templates',     dest: "layoutrtl1/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/api',     dest: "layoutrtl1/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/i18n',    dest: "layoutrtl1/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/images',     dest: "layoutrtl1/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/config',      dest: "layoutrtl1/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/directives',      dest: "layoutrtl1/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/controllers',      dest: "layoutrtl1/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/js/filters',      dest: "layoutrtl1/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/views',     dest: "layoutrtl1/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-1/RTL/assets/css/themes',     dest: "layoutrtl1/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layoutrtl1/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-1/RTL/master/_index.min.html', dest : 'layoutrtl1/index.html'},
            {src: 'LAYOUT-1/RTL/favicon.ico', dest : 'layoutrtl1/favicon.ico'},
            {src: 'LAYOUT-1/RTL/upload.php', dest : 'layoutrtl1/upload.php'}
        ]
    },
	layout2: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layout2/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layout2/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layout2/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layout2/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layout2/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/templates',     dest: "layout2/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/api',     dest: "layout2/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/i18n',    dest: "layout2/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/images',     dest: "layout2/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/config',      dest: "layout2/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/directives',      dest: "layout2/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/controllers',      dest: "layout2/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/js/filters',      dest: "layout2/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/views',     dest: "layout2/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/STANDARD/assets/css/themes',     dest: "layout2/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layout2/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-2/STANDARD/master/_index.min.html', dest : 'layout2/index.html'},
            {src: 'LAYOUT-2/STANDARD/favicon.ico', dest : 'layout2/favicon.ico'},
            {src: 'LAYOUT-2/STANDARD/upload.php', dest : 'layout2/upload.php'}
        ]
    },
    layoutrtl2: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layoutrtl2/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layoutrtl2/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layoutrtl2/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layoutrtl2/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layoutrtl2/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/templates',     dest: "layoutrtl2/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/api',     dest: "layoutrtl2/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/i18n',    dest: "layoutrtl2/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/images',     dest: "layoutrtl2/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/config',      dest: "layoutrtl2/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/directives',      dest: "layoutrtl2/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/controllers',      dest: "layoutrtl2/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/js/filters',      dest: "layoutrtl2/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/views',     dest: "layoutrtl2/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-2/RTL/assets/css/themes',     dest: "layoutrtl2/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layoutrtl2/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-2/RTL/master/_index.min.html', dest : 'layoutrtl2/index.html'},
            {src: 'LAYOUT-2/RTL/favicon.ico', dest : 'layoutrtl2/favicon.ico'},
            {src: 'LAYOUT-2/RTL/upload.php', dest : 'layoutrtl2/upload.php'}
        ]
    },
	layout3: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layout3/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layout3/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layout3/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layout3/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layout3/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/templates',     dest: "layout3/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/api',     dest: "layout3/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/i18n',    dest: "layout3/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/images',     dest: "layout3/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/config',      dest: "layout3/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/directives',      dest: "layout3/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/controllers',      dest: "layout3/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/js/filters',      dest: "layout3/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/views',     dest: "layout3/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/STANDARD/assets/css/themes',     dest: "layout3/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layout3/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-3/STANDARD/master/_index.min.html', dest : 'layout3/index.html'},
            {src: 'LAYOUT-3/STANDARD/favicon.ico', dest : 'layout3/favicon.ico'},
            {src: 'LAYOUT-3/STANDARD/upload.php', dest : 'layout3/upload.php'}
        ]
    },
    layoutrtl3: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layoutrtl3/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layoutrtl3/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layoutrtl3/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layoutrtl3/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layoutrtl3/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/templates',     dest: "layoutrtl3/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/api',     dest: "layoutrtl3/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/i18n',    dest: "layoutrtl3/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/images',     dest: "layoutrtl3/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/config',      dest: "layoutrtl3/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/directives',      dest: "layoutrtl3/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/controllers',      dest: "layoutrtl3/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/js/filters',      dest: "layoutrtl3/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/views',     dest: "layoutrtl3/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-3/RTL/assets/css/themes',     dest: "layoutrtl3/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layoutrtl3/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-3/RTL/master/_index.min.html', dest : 'layoutrtl3/index.html'},
            {src: 'LAYOUT-3/RTL/favicon.ico', dest : 'layoutrtl3/favicon.ico'},
            {src: 'LAYOUT-3/RTL/upload.php', dest : 'layoutrtl3/upload.php'}
        ]
    },
	layout4: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layout4/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layout4/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layout4/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layout4/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layout4/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/templates',     dest: "layout4/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/api',     dest: "layout4/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/i18n',    dest: "layout4/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/images',     dest: "layout4/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/config',      dest: "layout4/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/directives',      dest: "layout4/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/controllers',      dest: "layout4/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/js/filters',      dest: "layout4/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/views',     dest: "layout4/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/STANDARD/assets/css/themes',     dest: "layout4/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layout4/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-4/STANDARD/master/_index.min.html', dest : 'layout4/index.html'},
            {src: 'LAYOUT-4/STANDARD/favicon.ico', dest : 'layout4/favicon.ico'},
            {src: 'LAYOUT-4/STANDARD/upload.php', dest : 'layout4/upload.php'}
        ]
    },
    layoutrtl4: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layoutrtl4/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layoutrtl4/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layoutrtl4/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layoutrtl4/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layoutrtl4/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/templates',     dest: "layoutrtl4/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/api',     dest: "layoutrtl4/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/i18n',    dest: "layoutrtl4/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/images',     dest: "layoutrtl4/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/config',      dest: "layoutrtl4/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/directives',      dest: "layoutrtl4/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/controllers',      dest: "layoutrtl4/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/js/filters',      dest: "layoutrtl4/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/views',     dest: "layoutrtl4/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-4/RTL/assets/css/themes',     dest: "layoutrtl4/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layoutrtl4/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-4/RTL/master/_index.min.html', dest : 'layoutrtl4/index.html'},
            {src: 'LAYOUT-4/RTL/favicon.ico', dest : 'layoutrtl4/favicon.ico'},
            {src: 'LAYOUT-4/RTL/upload.php', dest : 'layoutrtl4/upload.php'}
        ]
    },
	layout5: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layout5/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layout5/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layout5/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layout5/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layout5/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/templates',     dest: "layout5/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/api',     dest: "layout5/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/i18n',    dest: "layout5/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/images',     dest: "layout5/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/config',      dest: "layout5/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/directives',      dest: "layout5/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/controllers',      dest: "layout5/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/js/filters',      dest: "layout5/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/views',     dest: "layout5/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/STANDARD/assets/css/themes',     dest: "layout5/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layout5/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-5/STANDARD/master/_index.min.html', dest : 'layout5/index.html'},
            {src: 'LAYOUT-5/STANDARD/favicon.ico', dest : 'layout5/favicon.ico'},
            {src: 'LAYOUT-5/STANDARD/upload.php', dest : 'layout5/upload.php'}
        ]
    },
    layoutrtl5: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layoutrtl5/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layoutrtl5/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layoutrtl5/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layoutrtl5/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layoutrtl5/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/templates',     dest: "layoutrtl5/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/api',     dest: "layoutrtl5/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/i18n',    dest: "layoutrtl5/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/images',     dest: "layoutrtl5/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/config',      dest: "layoutrtl5/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/directives',      dest: "layoutrtl5/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/controllers',      dest: "layoutrtl5/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/js/filters',      dest: "layoutrtl5/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/views',     dest: "layoutrtl5/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-5/RTL/assets/css/themes',     dest: "layoutrtl5/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layoutrtl5/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-5/RTL/master/_index.min.html', dest : 'layoutrtl5/index.html'},
            {src: 'LAYOUT-5/RTL/favicon.ico', dest : 'layoutrtl5/favicon.ico'},
            {src: 'LAYOUT-5/RTL/upload.php', dest : 'layoutrtl5/upload.php'}
        ]
    },
	layout6: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layout6/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layout6/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layout6/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layout6/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layout6/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/templates',     dest: "layout6/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/api',     dest: "layout6/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/i18n',    dest: "layout6/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/images',     dest: "layout6/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/config',      dest: "layout6/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/directives',      dest: "layout6/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/controllers',      dest: "layout6/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/js/filters',      dest: "layout6/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/views',     dest: "layout6/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/STANDARD/assets/css/themes',     dest: "layout6/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layout6/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-6/STANDARD/master/_index.min.html', dest : 'layout6/index.html'},
            {src: 'LAYOUT-6/STANDARD/favicon.ico', dest : 'layout6/favicon.ico'},
            {src: 'LAYOUT-6/STANDARD/upload.php', dest : 'layout6/upload.php'}
        ]
    },
    layoutrtl6: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "layoutrtl6/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "layoutrtl6/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "layoutrtl6/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/slick-carousel/slick/fonts', dest: "layoutrtl6/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/flag-icon-css/flags', dest: "layoutrtl6/assets/flags"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/templates',     dest: "layoutrtl6/templates"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/api',     dest: "layoutrtl6/assets/api"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/i18n',    dest: "layoutrtl6/assets/i18n"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/images',     dest: "layoutrtl6/assets/images"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/config',      dest: "layoutrtl6/assets/js/config"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/directives',      dest: "layoutrtl6/assets/js/directives"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/controllers',      dest: "layoutrtl6/assets/js/controllers"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/js/filters',      dest: "layoutrtl6/assets/js/filters"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/views',     dest: "layoutrtl6/assets/views"},
            {expand: true, src: "**", cwd: 'LAYOUT-6/RTL/assets/css/themes',     dest: "layoutrtl6/assets/css/themes"},
            {src: 'bower_components/slick-carousel/slick/ajax-loader.gif', dest : 'layoutrtl6/assets/css/ajax-loader.gif'},
            {src: 'LAYOUT-6/RTL/master/_index.min.html', dest : 'layoutrtl6/index.html'},
            {src: 'LAYOUT-6/RTL/favicon.ico', dest : 'layoutrtl6/favicon.ico'},
            {src: 'LAYOUT-6/RTL/upload.php', dest : 'layoutrtl6/upload.php'}
        ]
    }
};
